# Generated by Django 5.1.3 on 2025-01-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_stockquote_volume_weighted_average'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stockquote',
            managers=[
            ],
        ),
    ]
