# Generated by Django 5.1.3 on 2025-01-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_stockquote_managers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockquote',
            unique_together={('company', 'time')},
        ),
    ]
